version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: studbet-db
    environment:
      POSTGRES_DB: studbetdb
      POSTGRES_USER: studbetuser
      POSTGRES_PASSWORD: studbetpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./flyway-migration/fill-data.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studbetuser -d studbetdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: studbet-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
